### ISSUE TITLE
View selection not remembered or carried forward

### ISSUE THREAD

**Issue by maveric69** [doko-desuka/plugin.video.toonmania2#1]
I have to choose over and over list or wide list view every time I start the addon and each time I move around the pages or sections. Please save the last used view, allow the setting of a default view, and use the current view when going to the next page .etc
Thanks!

**Comment by doko-desuka** [comment]
Hi, let me confirm. Right now the sections screen (showing the All, #, A, B, C, D etc. folders) is hardcoded to be in grid layout, it's forced. You want to be able to change the layout for this screen?

Inside each of those folders there's shows \ movies, that use either WideList or InfoWall layouts depending on the "Use Grid Layout for Shows" setting.

Episode lists (for a specific show) just use the default (WideList).

**Comment by doko-desuka** [comment]
Hmm, okay, how about this. Three different settings:

- Choose layout for sections screen
- Choose layout for shows \ movies screen 
- Choose layout for episodes screen.

So you can turn each setting on/off and control the type of layout (WideList, InfoWall, Shift etc.) for each type of screen.

**Comment by maveric69** [comment]
I think the default solution you have is in line with other addons and seems great. As far as the operation use list as the example. I have to select list view 11 times for each and every page I go to where the shows are listed. When the grid option is off we have just two choices but it is still a pain. I use the grid option also because the Metadata is not filled in when not selected. So using the default option on all pages works wonders. I prefer list as my view or wide list when I have to. Your approach for defaults and remembering what was last selected make a huge difference!! Thanks and I can't wait for it!

**Comment by doko-desuka** [comment]
This is all I can do for now:
https://github.com/doko-desuka/plugin.video.toonmania2/raw/master/plugin.video.toonmania2-0.3.3.zip

**Comment by doko-desuka** [comment]
If you find a bug with that, drop by.

**Comment by doko-desuka** [comment]
(Oh and I forgot to say that the changes are in the addon settings, the new layout options.)

**Comment by Shahav** [comment]
Sorry was just now able to get to my emails...😭  Was the link you sent me
your repositories file manager address (If so i have alot of plugging in to
do...  LOL, Ha, Ha) so i can add source and put it into my browser and
install from zip file, click on repo zip & then YES i can watch my dub
anime shows in quality again.😄😁😇

Sherry

**Comment by doko-desuka** [comment]
In that 9Anime thread I linked you to the direct zip of this Toonmania2 add-on alone.  
In this thread I linked to the direct zip of the latest version of Toonmania2 alone, for @maveric69.

If you want my repository, I don't have a file manager address, only a zip file of it that you can [get in here](https://github.com/doko-desuka/doko.repository/releases).  
Inside that zip file there's just the icon and the addon.xml. If you install that repo zip, it'll point to these Github files and stay updated whenever I push new version -- then the file manager address won't be necessary.

**Comment by maveric69** [comment]
Yeah!! Initial update testing works great! Thanks dude. You rock

**Comment by doko-desuka** [comment]
Hi Shahav, read this: https://github.com/doko-desuka/doko-desuka.github.io
