### ISSUE TITLE
Higher quality streams

### ISSUE THREAD

**Issue by Cayz181299** [doko-desuka/plugin.video.toonmania2#3]
Would it be possible for the links to say what definition each host is, 480p,720p etc, plus more HD hosts?

**Comment by doko-desuka** [comment]
Hi. I noticed after some time that all those "hosts" are owned by them, and they all solve to the same url on the same domain... So it's not like Openload, streamango etc.  
It's just a facade.

All hosts have a single source quality listed as "normal", they don't have other qualities to pick unfortunately.
Thats why the "autoplay" setting is useful, as it makes no difference what host you choose.

I'm going to close this as I see no way to do what you want, but you can still comment on a closed issue if you want.
