### ISSUE TITLE
Latest updates not showing all pages

### ISSUE THREAD

**Issue by maveric69** [doko-desuka/plugin.video.toonmania2#4]
Under subbed anime, latest updates view. When you select ALL to see all shows, only two pages are shown. Only up to shows starting with letter O. There are many more shows from letter P to Z not shown. If you back out and just choose the single letter they are listed. Can you please fix the bug so all pages are ahown. I am not sure if this is the only area this problem exists with showing all pages.

**Comment by doko-desuka** [comment]
Hi @maveric69, thank you for the bug report. That sounds weird. It's showing all items in here, so I think it's related to the cache.

Can you try this?
First, make sure you have the latest version, it's 0.4.2 from today: [plugin.video.toonmania2-0.4.2.zip](https://github.com/doko-desuka/plugin.video.toonmania2/raw/master/plugin.video.toonmania2-0.4.2.zip)  
(If you have my repo installed then it should automatically update, if your auto-updates setting is on.)

Then try it again going to Subbed Anime -> Latest Updates.
If the same thing is still happening, then go back to the first menu, open Settings, go to the Cache category and select Clear Cache File. This clears your cache file so everything should be downloaded again from the source (if people abuse this it might call their attention from all the web traffic...).  

Anyway, that should work. After this you don't need to keep clearing the cache file like that, it will manage itself.

**Comment by maveric69** [comment]
I have the repo and new update and cleared cache and issue still jappens. Only 2 pages shown when selecting latest updates and then ALL. This happens in subbed as well as dubbed. Dubbed only shows up to letter T. Subbed up to letter O. I have view set to LIST and the default of 30 items. I have cleared cache and closed and reopen addon. Please see what you get using the described view and count. Popular view shows 8 pages but I am not sure if that is all or not. Let me know if you need anything else.

**Comment by doko-desuka** [comment]
@maveric69 woah, you're right. When I turned on thumbnails in the settings (the only way that it will separate in pages), it was the same as you described.

After some investigation, this is due to differences between Python 2 (what Kodi 17.6 uses) and Python 3 (what I was using to test codes and formulas etc.). It was a line of code that calculated the pages.  

It's fixed now, with your name in the changelog:  
[plugin.video.toonmania2-0.4.3.zip](https://github.com/doko-desuka/plugin.video.toonmania2/raw/master/plugin.video.toonmania2-0.4.3.zip)

**Comment by maveric69** [comment]
Yippie! Things look good with initial testing. Thanks for the nod. 
Now if I can just get a local Watch List/Favorites life would easy :)
Thanks for the quick fix and update
