### ISSUE TITLE
Vidics.to

### ISSUE THREAD

**Issue by bjgood** [doko-desuka/plugin.video.toonmania2#6]
Hey doko,
If you get the chance why not look at resurrecting vidics.to as a source. You know...the one that was in Genesis a long time ago. A lot of the code is still relevant. Its address is https://www.vidics.to. Resolveurl has a vidics.tv but I think the link in it is dead. Even back in the good-ole-days vidics.to was a great source for TV episodes and it still is. You can find Genesis at the kodil repo.

If need be I can post the code here.

Just a suggestion.

Later...
Bob

**Comment by doko-desuka** [comment]
Hi @bjgood,
Thanks for the suggestion. I'm sorry to say I'm out of time for scrapers at the moment =(
Maybe later.

**Comment by bjgood** [comment]
Sorry for posting in this section. I had no other way to give my suggestion about vidics.to.

Again, sorry.
Bob

**Comment by doko-desuka** [comment]
No problem bro =D  
I know you opened this as a way to send me a message.

**Comment by doko-desuka** [comment]
@jewbmx Like I said, I can't work on this.  
Please post that in the I-A-C repos, it's their concern now.

**Comment by doko-desuka** [comment]
https://github.com/I-A-C/script.module.lambdascrapers/pull/20

**Comment by bjgood** [comment]
Nice one, doko! Thanks, buddy. :).
